### ISSUE TITLE
[THIBAUT] TO DO

### ISSUE THREAD

**Issue by Thibaut-Lacroix** [ecvwebdesign/ECV-D5-dig-2016-2017-new#93]
- Responsive header
- Submit button in safari
- Taille police pas responsive
- Police d'icone pas assez lisible sur mobile
- Icone pas responsive
- contact form pas centré verticalement

**Comment by leacoues** [comment]
👍

**Comment by Thibaut-Lacroix** [comment]
- Responsive header = DONE
- Submit button in safari = DONE
- Taille police pas responsive = DONE
- Police d'icone pas assez lisible sur mobile = DONE
- Icone pas responsive = DONE
- contact form pas centré verticalement = DONE

**Comment by Thibaut-Lacroix** [comment]
DONE !
